development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: share_devel
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['DEVEL_DB_PASS'] %>
  host: localhost
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: share_test
  username: root
  password: <%= ENV['TEST_DB_PASS'] %>
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
